name: SpawnHints

on:
  create

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore NuGet Packages
      run: nuget restore SpawnHints/SpawnHints.sln
      
    - name: Build
      run: msbuild SpawnHints.sln /p:Configuration=Debug
      
    - name: Upload EXE
      uses: actions/upload-artifact@v2.2.4
      with:
        name: SpawnHints
        path: /home/runner/work/CS3-Projects/CS3-Projects/FactorialSum/FactorialSum/bin/Debug/netcoreapp3.1/
