name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore dependencies
      run: dotnet restore FactorialSum/FactorialSum.sln
    - name: Build
      run: dotnet build --no-restore FactorialSum/FactorialSum.sln
    - name: Upload EXE
      uses: actions/upload-artifact@v2.2.4
      with:
        name: FactorialSum.exe
        path: /home/runner/work/CS3-Projects/CS3-Projects/FactorialSum/FactorialSum/bin/Debug/netcoreapp3.1/
